### PR TITLE
Fix eventSource connection issue

### LINKED ISSUE #3: [Group-IB Feedback] EventSource connection issues
It's important close connections and clear any subscriptions, intervals, timeouts when a component unmounts, to prevent some unexpected behaviour when the component disappears. For instance, here ([https://github.com/PallonCX/typescript-assignment/…](https://github.com/PallonCX/typescript-assignment/blob/main/client/src/pages/Main.tsx#L19-L37)) the EventSource connection should be closed when the component unmounts. Also, the connection should be initialized in the root component. Right now a new connection is created every time we switch pages (go to Settings and back to Main).

### PR DESCRIPTION
**Pull request by PallonCX**
Closes #3 

**Changes made:**
1. Initialized the EventSource connection in the root component. The EventSource connection is closed when the App component unmounts.
2. EventListeners for Main are added when Main is mounted (i.e. go to Main page), and removed when Main is unmounted (i.e. go to Setting page). Timeouts are cleared when Main component unmounts.

### CODE REVIEW

File: client/src/App.tsx [hunk 1]
```diff
@@ -9,6 +9,16 @@ const App = () => {
...
+    const [eventSource, setEventSource] = useState<EventSource | null>(null);
+
+    useEffect(() => {
+        const source = new EventSource('http://localhost:9000/events');
+        setEventSource(source);
+
+        return () => {
+            source.close();
+        };
+    }, []);
```
Comment (PallonCX) [inline client/src/App.tsx:21]: Initialized the EventSource connection in the root component. The EventSource connection is closed when the App component unmounts.

File: client/src/pages/Main.tsx [hunk 2]
```diff
@@ -34,7 +35,17 @@ const Main: React.FC<MainProps> = ({ messageCount, messagePosition, messageDisap
...
+        eventSource.addEventListener('message', handleMessageEvent);
+
+        return () => {
+            eventSource.removeEventListener('message', handleMessageEvent);
+
+            Object.values(messageTimeouts).forEach(timeoutId => {
+                clearTimeout(timeoutId);
+            });
+        };
+    }, [eventSource, messageDisappearTime]);
```
Comment (PallonCX) [inline client/src/pages/Main.tsx:48]: EventListeners for Main are added when Main is mounted (i.e. go to Main page), and removed when Main is unmounted (i.e. go to Setting page). Timeouts are cleared when Main component unmounts.

File: client/src/pages/Main.tsx [hunk 3]
```diff
@@ -12,14 +13,14 @@ interface Message {
     content: string;
 }
 
-const Main: React.FC<MainProps> = ({ messageCount, messagePosition, messageDisappearTime }) => {
+const Main: React.FC<MainProps> = ({ eventSource, messageCount, messagePosition, messageDisappearTime }) => {
```
Comment (PallonCX) [inline client/src/pages/Main.tsx:16]: The Main component no longer initialised EventSource connection. It retrieves it from the root component.
